---
stages:
  - build

build jar:
  image: gradle:6-jdk11
  stage: build
  before_script:
    - apt update
    - apt install -y libatomic1  # needed for protoc
  script:
    - gradle test
    - gradle build
    - gradle jar
  artifacts:
    paths:
      - build/libs/
